name: Arduino CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  compile:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v6
      - name: Compile examples
        uses: arduino/compile-sketches@v1
        with:
          fqbn: arduino:avr:uno
          libraries: |
            - source-path: ./
          sketch-paths: |
            examples
